  * **Campaign Effectiveness Report**  
    * **Business Objective:** Evaluate the performance of advertising campaigns across digital platforms and understand campaign performance in terms of user engagement, cost efficiency, and resulting transactions.  
    * **Required Insight:**  
    
      * Volume of exposure (e.g., ad impressions) for each campaign across time.  -- count event_type by camp name by date    
      /*select business_date,campaign_id,campaign_name,campaign_type,event_type,count(event_type) as no_of_event
		 from report_campaign_effectiveness_report
		 group by business_date,campaign_id,campaign_name,campaign_type,event_type*/
      
      * Level of user interaction with the ads (e.g., clicks).  -- count event_type
       /*select customer_id,event_type,count(event_type) as no_of_event
		 from report_campaign_effectiveness_report
		 where event_type is not null
		 group by customer_id,event_type*/
      
      * Number of users who completed a purchase after interacting with the ad.  -- count distinct is_user_completed_purchase_after_interacting
       /*select count (distinct customer_id) no_of_cust
		 from report_campaign_effectiveness_report
		 where lower(order_status) = 'completed'
		 and is_user_completed_purchase_after_interacting is true*/
      
      * Cost associated with running the campaign.  -- sum ad_cost by campaign
      * Total revenue attributed to each campaign.  -- sum total amount
      * Marketing efficiency metrics (e.g., cost per acquired customer and return on advertising spend).  -- cost per acquired cust group by cust_id  #ofcust/cost
      /* --answer for 3 question above
        select campaign_id,campaign_name,campaign_type,sum(ad_cost) total_cost,count(distinct customer_id) no_of_cust,sum(total_amount) total_amount
		,sum(ad_cost)/count(distinct customer_id) as cpac
		,sum(total_amount)/sum(ad_cost)  as roas
		from report_campaign_effectiveness_report
		where campaign_id is not null
		group by campaign_id,campaign_name,campaign_type*/
      
      
  * **Customer Acquisition Report**  
    * **Business Objective:** Understand how successful each campaign is at acquiring new customers and how those customers behave post-acquisition.  
    * **Required Insight:**
    
      * Number of first-time customers attributed to a specific campaign.  -- count dinstict cust_id per campaign
       /*select campaign_id,campaign_name,campaign_type,count(distinct customer_id) no_of_cust
		 from report_customer_acquisition_report
		 where campaign_id is not null
		 group by campaign_id,campaign_name,campaign_type*/
      
      * Spending behavior of those customers (e.g., average purchase value, number of repeat orders).  -- group by cust_id total_amount/order = avg. sum order
       /*select customer_id,sum(total_amount) total_amount,count(order_id) total_order
		 ,sum(total_amount)/count(order_id) as avg_values_per_cust
		 from report_customer_acquisition_report
		 group by customer_id*/
      
      * How long customers remain active after their first purchase.  -- find first order and last order >> new column
       /*select customer_id,day_of_active
		 from report_customer_acquisition_report
		 group by customer_id,day_of_active*/
      
      * Average time between first interaction and first purchase.  -- diff interact datetime - order datetime >> avg
       /*select  avg(diff_interact_order_min)
 		from report_customer_acquisition_report*/
      * Total marketing cost spent to acquire these customers.  -- sum adcost
      /*select  sum(ad_cost)
		from report_customer_acquisition_report*/
 
      * Segmentation by channel/platform for comparison.  -- segment from cust master count distinct cust_id group by channel,platform,segment
       /*select  customer_segment,platform,count(distinct customer_id) as no_of_cust
		 from report_customer_acquisition_report
		 where campaign_id is not null
		 group by customer_segment,platform*/
 
  * **Retargeting Performance Report**  
    * **Business Objective:** Evaluate retargeting campaigns that aim to bring back previous or inactive customers and see if the strategy effectively re-engages past users.  
    * **Required Insight:**  
      * Number of previously active customers targeted in each retargeting campaign.  
      * Proportion who returned and placed another order.  
      * Total spend generated by retargeted customers.  -- campaign type + total_amount
      * Time gap between original and returning orders.  
      * Retention behavior after retargeting (do they continue to use the platform?).  
      * Comparison across campaign types or targeting segments.

      -- create model
with trans_with_act AS (
select datetrunc('day', order_datetime) as business_date 
,t.order_id
,t.customer_id
,t.restaurant_id
,t.driver_id 
,campaign_id
,order_datetime
,pickup_datetime
,delivery_datetime
,order_status
,delivery_zone
,total_amount,payment_method 
,is_late_delivery
,delivery_distance_km 
,interaction_datetime
,event_type
,platform
,device_type
,ad_cost 
from order_transactions t
left join campaign_interactions cin
on t.order_id = cin.order_id 
)
,model_curated_active_after_purchase as (
 select customer_id
 ,min(order_datetime) min_order_datetime
 ,max(order_datetime) max_order_datetime
 ,date_diff('day',min(order_datetime),max(order_datetime)) day_of_active
 from trans_with_act
 group by customer_id
)

,model_curated_marketing_transaction as (
 select t.*
 ,case when interaction_datetime <= order_datetime then True
 else false
 end is_user_completed_purchase_after_interacting
 ,date_diff('min',interaction_datetime,order_datetime) as diff_interact_order_min
 from trans_with_act t
 --and business_date between start_date and end_date
 )

 ,report_campaign_effectiveness_report as (
 select a.*
 ,campaign_name
 ,start_date
 ,end_date
 ,campaign_type
 ,objective
 ,channel
 ,targeting_strategy
 from model_curated_marketing_transaction a
 left join campaign_master c
 on a.campaign_id = c.campaign_id
 )
 
 -- create report_customer_acquisition_report 
 ,report_customer_acquisition_report as (
 select t.*
 ,day_of_active
 ,customer_segment
 ,campaign_name
 ,start_date
 ,end_date
 ,campaign_type
 ,objective
 ,channel
 ,targeting_strategy
 from model_curated_marketing_transaction t
 left join model_curated_active_after_purchase a
 on t.customer_id = a.customer_id
 left join customers_master c
 on t.customer_id = c.customer_id
 left join campaign_master cm
 on t.campaign_id = cm.campaign_id
 )
 

 
